// src/features/auth/api/authApi.ts
import { baseApi } from '@/shared/api/baseApi'
import type { DummyJsonAuthDto } from '@/shared/types/auth'

interface LoginRequest { username: string; password: string }

export const authApi = baseApi.injectEndpoints({
    endpoints: (build) => ({
        login: build.mutation<DummyJsonAuthDto, LoginRequest>({
            query: (body) => ({
                url: '/auth/login',
                method: 'POST',
                body,
            }),
            invalidatesTags: ['Auth'],
        }),
    }),
})

// NOTE: Export hooks generated by RTK Query
export const { useLoginMutation } = authApi
